In [1]:
import numpy as np
b=np.array([30,45,67])
c=np.array([23,67,45])
print(b+c)

    

[ 53 112 112]


In [31]:
arr1=np.array([90,34,78,56,27,62])
print(arr1[0:])

[90 34 78 56 27 62]


In [33]:
print(arr1[2:4])

[78 56]


In [61]:
arr2=np.array([[[45,23],[93,89]],[[33,55],[9,45]]])
print(arr2[0,1,0:1])


[93]


In [67]:
print(np.size(arr2))
print(np.shape(arr2))
print(np.ndim(arr2))


8
(2, 2, 2)
3


In [13]:
import numpy as np
m=np.array([23,67,98,54])
p=np.array([12,34,56,65])
print(np.divide(m,p))

[1.91666667 1.97058824 1.75       0.83076923]


In [19]:
import numpy as np
m=np.array([23,67,98,54])

print(np.sqrt(m))

[4.79583152 8.18535277 9.89949494 7.34846923]


In [21]:
import numpy as np
b=np.array([2,3,4,5])
c=np.array([2])
print(np.power(b,c))

[ 4  9 16 25]


In [35]:
import numpy as np
arr1=np.array([[[12,13],[14,15]],[[16,17],[18,19]]])
arr2=np.array([[[20,21],[22,23]],[[24,25],[26,27]]])
print(np.concatenate([arr1,arr2],axis=1))

[[[12 13]
  [14 15]
  [20 21]
  [22 23]]

 [[16 17]
  [18 19]
  [24 25]
  [26 27]]]


In [3]:
import numpy as np
arr1=np.array([[2,3],[18,19]])
arr2=np.array([[20,21],[26,27]])
print(arr1)
print(arr2)
print(np.hstack([arr1,arr2]))
print("  ")
print(np.vstack([arr1,arr2]))

[[ 2  3]
 [18 19]]
[[20 21]
 [26 27]]
[[ 2  3 20 21]
 [18 19 26 27]]
  
[[ 2  3]
 [18 19]
 [20 21]
 [26 27]]


In [49]:
print(np.vstack([arr1,arr2]))

[[ 2  3]
 [18 19]
 [20 21]
 [26 27]]


In [65]:
import numpy as np
a=np.array([[2,3,4,5,6],[7,8,9,10,11]])
b=np.array_split(a,2)
print(b)

[array([[2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11]])]


In [3]:
import numpy as np
a=np.array([34,67,34,98])
print(np.append(a,23))

[34 67 34 98 23]


In [5]:
print(np.insert(a,3,78))

[34 67 34 78 98]


In [11]:
arr2=np.array([[2,3],[8,9]])
print(np.insert(arr2,[34,78],axis=0))

TypeError: insert() missing 1 required positional argument: 'values'

In [1]:
import numpy as np

arr1=np.array([[12,34,51,78],[34,21,56,95],[1,2,3,4]])
print(arr1)
print()
print(np.delete(arr1,[2,3],axis=-1))

[[12 34 51 78]
 [34 21 56 95]
 [ 1  2  3  4]]

[[12 34]
 [34 21]
 [ 1  2]]


In [1]:
import numpy as np
arr=np.array([34,89,23,67,54,12,34,5,6,89,100])
print(np.sort(arr))

[  5   6  12  23  34  34  54  67  89  89 100]


In [5]:
arr1=np.array([12,45,78,345,56])
s=np.where(arr1%2==0)
print(s)

(array([0, 2, 4], dtype=int64),)


In [9]:
print(np.sort(arr1))
print(np.searchsorted(arr1,56))

[ 12  45  56  78 345]
2


In [17]:
arr6=np.array(['new','new green','red-green'])
fi=arr6 == 'new'
print(arr6[fi])


['new']


In [23]:
import numpy as np
arr1=np.array([23,56,87,90,12,45,677,89,78])
print(np.sum(arr1))
print(np.min(arr1))
print(np.max(arr1))
print(np.mean(arr1))
print(np.cumsum(arr1))
print(np.cumprod(arr1))

1157
12
677
128.55555555555554
[  23   79  166  256  268  313  990 1079 1157]
[         23        1288      112056    10085040   121020480  1150954304
  1806983232  1907717696 -1521875072]


In [45]:
import numpy as np
price=np.array([12,34,56,87,65])
quantity=np.array([2,4,7,9,8])
print(price,quantity)
print()
n=np.cumprod([price,quantity] ,axis=1)
print(n)
print(n[1,4].sum())



[12 34 56 87 65] [2 4 7 9 8]

[[       12       408     22848   1987776 129205440]
 [        2         8        56       504      4032]]
4032


In [3]:
import numpy as np
baked=[12,56,54,92,49,62]
arr=np.array(baked)
print(np.mean(arr))
print(np.median(arr))

54.166666666666664
55.0


In [11]:
import statistics as stat

ar=np.array([12,12,12,34,56,78,90,8,55,200])
print(stat.mode(ar))
print(np.std(ar))
print(np.var(ar))

12
55.65258304876782
3097.21


In [13]:
price=np.array([12,34,56,78,90])
sale=np.array([90,78,56,34,12])
print(np.corrcoef([price,sale]))


[[ 1.         -0.98514851]
 [-0.98514851  1.        ]]


In [27]:
import numpy as np
a=np.array([[0, 3, '0', 22.0, 1, '0'],
       [1, 1, '1', 38.0, 1, '1'],
       [1, 3, '1', 26.0, 0, '0'],
       [1, 1, '1', 35.0, 1, '0'],
       [0, 3, '0', 35.0, 0, '0']])


In [29]:
a=np.delete(a,[2,4,5],axis=1)
a

array([['0', '3', '22.0'],
       ['1', '1', '38.0'],
       ['1', '3', '26.0'],
       ['1', '1', '35.0'],
       ['0', '3', '35.0']], dtype='<U32')